### ISSUE TITLE
Not free Software

### ISSUE THREAD

**Issue by nextl00p** [TripSit/tripmobile#37]
I want to bundle this App for F-Droid ( https://f-droid.org ). Infact, I already got a working build recipe.

The only problem with this app is its licence. This app is not free software and the choice of licence is not verry wise. See: https://wiki.creativecommons.org/index.php/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F

For a list of compatible linceces see https://f-droid.org/wiki/page/Inclusion_Policy and especially https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses .

A licence change requires that all developers who already contributed agree with this change.

**Comment by nextl00p** [comment]
See also https://f-droid.org/wiki/page/Inclusion_Policy @EddieCurtis

**Comment by EddieCurtis** [comment]
I suggest the MIT licence but I will speak to other contributors and try to come up with an agreement.

**Comment by nextl00p** [comment]
Fixed with #38
