### ISSUE TITLE
TripSit KVIrc on GitHub?

### ISSUE THREAD

**Issue by davidhedlund** [TripSit/tripmobile#42]
Where is the bug tracker for [TripSit KVIrc](https://tripsit.me/tripsitapp/)?

**Comment by LunaUrsa** [comment]
That download is basically the KVIRC version (at the time) plus some settings to have it auto-connect to TripSit. I suppose we could put the settings file online so i can be used when KVIRC updates.

**Comment by LunaUrsa** [comment]
We'll be looking into a new irc client for the app
