### ISSUE TITLE
Make the wiki open for anyone to edit

### ISSUE THREAD

**Issue by davidhedlund** [TripSit/tripmobile#43]
Currently it's **extremly** hard to reach someone to give you editing permission to the wiki. I've tried a number of times and eventually gave up; This is completely counter productive and nonsense in my opinion. You waste the time of people that want to help, and you waste material that could be added to those people when they give up.

* Why is not the forum open to edit for anyone?

* Can you please give everyone edit permission?

* Can you at least add an email that can be used to request editing permission on the wiki; eg create admin@wiki.tripsit.me and add it to the [login](https://wiki.tripsit.me/wiki/Special:UserLogin) page?

**Comment by TeknoShamin** [comment]
Hey David, 

Which site are you referring to? 

I just created a new account on wiki.tripsit.me and it seems to have editing permissions?

**Comment by davidhedlund** [comment]
@TeknoShamin Please make an edit and give me the link so I can verify that you could edit.

**Comment by davidhedlund** [comment]
https://github.com/TripSit/welcome/issues/3

**Comment by davidhedlund** [comment]
@TeknoShamin Please respond at https://github.com/TripSit/welcome/issues/3
